name: Update NuGet

on: [push]

jobs:
  build:
    runs-on: windows-latest

    name: Publish Nuget Package
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Run Tests
        run:
          dotnet test "./tests/Blend.ActionQueue.Tests/Blend.ActionQueue.Tests.csproj"
      - name: Build Package
        run:           
          dotnet build -c Release "./src/Blend.ActionQueue/Blend.ActionQueue.csproj"
      - name: Package Release
        run:           
          dotnet pack -c Release --no-build -o out "./src/Blend.ActionQueue/Blend.ActionQueue.csproj"
      - name: Publish Nuget to GitHub registry
        run: ls .\out\*.nupkg | foreach { dotnet nuget push $_ -s https://nuget.pkg.github.com/blendinteractive/index.json -k $env:GITHUB_TOKEN }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
